function getTicker() {
    return([{key: "1",
            text: "January",
            value: "January"},
            {key: "2",
            text: "February",
            value: "February"},
            {key: "3",
            text: "March",
            value: "March"},
            {key: "4",
            text: "April",
            value: "April"},
            {key: "5",
            text: "May",
            value: "May"},
            {key: "6",
            text: "June",
            value: "June"},
            {key: "7",
            text: "July",
            value: "July"},
            {key: "8",
            text: "August",
            value: "August"},
            {key: "9",
            text: "September",
            value: "September"},
            {key: "10",
            text: "October",
            value: "October"},
            {key: "11",
            text: "November",
            value: "November"},
            {key: "12",
            text: "December",
            value: "December"},
    ])
}

export default getTicker();